[pytest]

testpaths = tests

python_files = test_*.py
python_functions = test_*

addopts =
    -v
    --reruns 3
    --html=reports/report.html
    --self-contained-html
    --screenshot=only-on-failure
    --tracing=retain-on-failure